In [7]:
import pandas as pd
import numpy as np

In [8]:
dat = pd.read_csv("stockData.csv")

In [9]:
dat.describe()

,SPX Index,TSLA US Equity,AAPL US Equity,NKE US Equity,AMZN US Equity,WMT US Equity,KO US Equity,XAU Curncy,CL1 Comdty,USGG10YR Index,USGG2YR Index
count,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000,1434.000000
mean,3224.526764,306.741641,82.312997,97.658424,107.387012,112.862092,50.122713,1532.728257,60.157001,1.983544,1.376885
std,720.211177,339.210243,45.999494,34.732270,43.580422,25.208714,5.905456,265.545802,18.118752,0.751622,0.944627
min,2237.400000,35.794000,28.955000,50.830000,37.494000,65.660000,37.560000,1147.500000,-37.630000,0.506900,0.101300
25%,2682.282500,60.779000,43.558500,68.872500,78.509000,91.537500,45.532500,1281.990000,49.820000,1.479025,0.224725
50%,2933.075000,71.474000,56.790000,87.435000,94.164500,114.960000,48.895000,1485.920000,57.840000,2.091450,1.425650
75%,3821.500000,642.975000,126.580750,129.707500,156.286750,138.362500,54.282500,1802.480000,68.080000,2.619550,2.266175
max,4796.560000,1229.910000,182.010000,177.510000,186.570000,159.870000,66.210000,2063.540000,123.700000,3.473300,3.426700